name: CI
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'package.json'
      - 'yarn.lock'
      - 'release.config.js'
      - '.github/workflows/ci.yml'
    branches:
      - '*'
      - '**'
      - '!master'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      packages: write
      contents: write

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: ci.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Yarn
        run: yarn install --frozen-lockfile

      - name: Test
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # yarn genall
          yarn buildall
          yarn test

      - name: Test APP
        run: |
          ./test-app/run.sh

      - name: Release Prep
        run: |
          npm i -g semantic-release @semantic-release/git @semantic-release/npm @semantic-release/github conventional-changelog-conventionalcommits @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec

      - name: Release
        run: |
          semantic-release --debug --no-ci
          ./publish.sh $CI_REF_NAME
