name: CI
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'package.json'
      - 'yarn.lock'
      - 'release.config.js'
      - '.github/workflows/ci.yml'
    branches:
      - '*'
      - '**'
      - '!master'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      packages: write
      contents: write

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: ci.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Yarn
        run: yarn install --frozen-lockfile

      - name: Test
        run: |
          # yarn genall
          yarn buildall
          yarn test

      - name: Release Prep
        run: |
          npm i -g semantic-release @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits semantic-release-monorepo

      - name: Release
        run: |
          # npx semantic-release --no-ci --debug
          # npx multi-semantic-release --debug --no-ci --dry-run
          npx lerna exec --concurrency 1 -- semantic-release -e semantic-release-monorepo --debug --no-ci --dry-run
