name: genql-runtime Npm Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cd genql-runtime && yarn
      - run: cd genql-runtime && yarn test
      - run: cd genql-runtime && yarn build
      - name: Bump version
        uses: remorses/bump-version@js
        with:
          version_file: genql-runtime/VERSION
          prefix: genql-runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cd genql-runtime && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
