name: Release
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'yarn.lock'
    branches:
      - 'master'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  Release:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      packages: write
      contents: write

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: release.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Yarn
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn install --frozen-lockfile --ignore-scripts
          yarn buildall
          yarn install --frozen-lockfile --ignore-scripts
          yarn genall
          yarn test

      - name: Build and Test Demo APP
        run: |
          ./demo-app/build-and-test.sh

      - name: Release Prep
        run: |
          npm i -g semantic-release @semantic-release/git @semantic-release/npm @semantic-release/github conventional-changelog-conventionalcommits @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec

      - name: Test & Release
        run: |
          semantic-release --debug --no-ci
          ./publish.sh master
